trigger:
  branches:
    include:
    - main
    exclude:
    - feature/*
    - development

pool:
  vmImage: windows-2019

stages:
  - stage: Build
    jobs:
      - job: Create_artifact
        steps:
        - task: CopyFiles@2
          inputs:
            Contents: |
              **
              !*.gitignore
              !*.yml
              !*.md
              !**\.git\**
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'modules'
            publishLocation: 'Container'